### ISSUE TITLE
Consider using TypeScript

### ISSUE THREAD

**Issue by wbhob** [clux/operators#1]
TypeScript is powerful, well-tested, and well-typed, and could take this library to the next level for many developers. I'd be happy to open a PR if you'd like me to do so (just let me know!)

**Comment by clux** [comment]
Hey, I appreciate your interest, but this library should just remain in basic maintenance mode at this point. Not going to do any big build changes or even publish new versions (unless bugs are found). Nothing against typescript though; it's nice.
